version: '3.9'
services:
  db:
    image: postgres:16
    container_name: campify-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: Campify
      POSTGRES_PASSWORD: IWT26
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: